title: Fernand T Alvarez # your name (or website title) here
logo: "https://media-exp1.licdn.com/dms/image/C4E03AQHWgU90-eYd9Q/profile-displayphoto-shrink_400_400/0/1572300503636?e=1649894400&v=beta&t=HdMeUfQ_fnS80kVCP2aQIG6EYCdEwxDUqvGbdDhQ478" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  GIS Analyst for the City of Palm Springs 
  <br><br>
  A diversified GIS Professional seeking a mangagerial position. 
  <br><br>
  <a href="https://www.linkedin.com/in/fernando-alvarez-228b1498/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
