title: Fernand T Alvarez # your name (or website title) here
logo: "https://i.ibb.co/fdphF4P/Fernando-Alvarez-IT.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  GIS Analyst for the City of Palm Springs 
  <br><br>
  A diversified GIS Professional seeking a mangagerial position. 
  <br><br>
  Hello, My name is Ferando, thank you for taking the time to view my Github Page. As you navigate through my page, you will oberve that my background in GIS is quite extensive. I have over 10 years of expereince with positions with United States Army, San Bernardino County, and The City of Palm Springs/
  <a href="https://www.linkedin.com/in/fernando-alvarez-228b1498/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
